"""
Manual regression: oversized skip/limit must return 422, not 500 (``skip_limit_bounds``).

================================================================================
WHAT THIS IS (plain English)
================================================================================

STS list endpoints accept integer ``skip`` and ``limit`` query params. Non-integer
or negative values already return HTTP 422. Values that are numeric but absurdly
large currently cause HTTP 500 on most paginated routes (likely Neo4j / int overflow
downstream). The product expectation is HTTP 422 with a detail message that names
the out-of-range param — same class of validation failure as non-integers.

This test GETs every discovered in-scope skip/limit endpoint once with a ticket-scale
``skip`` and once with a ticket-scale ``limit``, and asserts status 422 (never 500).

**Excluded** (already tolerate huge values or have no skip/limit): ``/models/``,
``/model/{handle}/versions``, and all ``/count`` endpoints.

Until STS is fixed, this suite is expected to FAIL against QA. After the fix, it
should PASS and guard against regression.

================================================================================
WHERE THE PATHS COME FROM
================================================================================

Same discovery + OpenAPI generation as the autogenerated suite:
``discover()`` + ``generate_cases(..., include_negative=True)``. Paths are taken
from cases whose ``operation_id`` ends with ``__bad_query_skip`` (integer skip +
documented 422), then filtered for exclusions.

================================================================================
HOW TO RUN
================================================================================

::

    pytest tests/test_manual/test_skip_limit_upper_bound.py -m skip_limit_bounds -v

Or::

    bash scripts/run_manual_tests.sh -m skip_limit_bounds

Uses ``STS_BASE_URL`` (default QA).
"""
from __future__ import annotations

import json
import logging
from typing import Any

import pytest

from sts_test_framework.client import APIClient, full_url
from sts_test_framework.config import bundled_spec_path, sts_base_url

logger = logging.getLogger(__name__)

# Ticket-scale values that currently trigger 500 on STS QA (edps / edp / other lists).
HUGE_SKIP = (
    "4895634985374589345743875634895349852346975645279235406234957623496157329"
    "4875239586324756324798567349543"
)
HUGE_LIMIT = "999999999999999999999999"


def _is_excluded_path(path: str) -> bool:
    """True for /models/, .../versions, and /count routes (out of scope for this bug)."""
    p = (path or "").rstrip("/")
    if p == "/models" or path in ("/models/", "/models"):
        return True
    if p.endswith("/versions"):
        return True
    if p.endswith("/count") or "/count/" in (path or ""):
        return True
    return False


def _collect_targets() -> list[tuple[str, str]]:
    """
    Build (path, param_name) pairs via live discover + generate_cases.

    Returns an empty list if the bundled spec is missing or discovery finds nothing.
    """
    from sts_test_framework.client import APIClient as _Client
    from sts_test_framework.discover import discover
    from sts_test_framework.generator import generate_cases
    from sts_test_framework.loader import load_spec

    spec_path = bundled_spec_path()
    if not spec_path.exists():
        return []

    spec = load_spec(spec_path)
    client = _Client(sts_base_url())
    test_data = discover(client)
    cases = generate_cases(spec, test_data, include_negative=True)

    paths: list[str] = []
    seen: set[str] = set()
    for case in cases:
        op_id = str(case.get("operation_id") or "")
        if not op_id.endswith("__bad_query_skip"):
            continue
        path = case.get("path") or ""
        if not path or _is_excluded_path(path):
            continue
        if path in seen:
            continue
        seen.add(path)
        paths.append(path)

    targets: list[tuple[str, str]] = []
    for path in paths:
        targets.append((path, "skip"))
        targets.append((path, "limit"))
    return targets


def _detail_mentions_param(detail: Any, param_name: str) -> bool:
    """
    True if FastAPI-style detail (str or list of error objects) identifies ``param_name``.

    Accepts string detail containing the name, or list items with loc/msg/input fields.
    """
    needle = param_name.lower()
    if isinstance(detail, str):
        return needle in detail.lower()
    if isinstance(detail, list):
        for item in detail:
            if isinstance(item, str) and needle in item.lower():
                return True
            if not isinstance(item, dict):
                continue
            blob = json.dumps(item, default=str).lower()
            if needle in blob:
                return True
            loc = item.get("loc")
            if isinstance(loc, (list, tuple)) and any(
                str(part).lower() == needle for part in loc
            ):
                return True
        return False
    if isinstance(detail, dict):
        return needle in json.dumps(detail, default=str).lower()
    return False


def _probe_failure(
    api_client: APIClient, path: str, param_name: str
) -> str | None:
    """
    Run one oversized skip/limit GET. Return a failure message, or None on success.
    """
    if param_name == "skip":
        params: dict[str, Any] = {"skip": HUGE_SKIP}
    else:
        params = {"skip": 0, "limit": HUGE_LIMIT}

    url = full_url(api_client, path, params)
    print(f"\n--- oversized {param_name}: {path} ---")
    print(f"  GET {url}")

    res = api_client.get(path, params=params)
    body_preview = (res.body or "")[:500]
    print(f"  HTTP {res.status_code} in {res.duration:.3f}s")
    print(f"  body[:500]={body_preview!r}")

    if res.status_code == 500:
        return (
            f"STS GET {url} returned 500 Internal Server Error for oversized "
            f"{param_name}; expected 422. body[:500]={body_preview!r}"
        )
    if res.status_code != 422:
        return (
            f"STS GET {url} expected 422 for oversized {param_name}, "
            f"got {res.status_code}. body[:500]={body_preview!r}"
        )

    data = res.json()
    if not isinstance(data, dict):
        return (
            f"STS GET {url}: 422 body should be a JSON object, "
            f"got {type(data).__name__}"
        )
    detail = data.get("detail")
    if detail is None:
        return f"STS GET {url}: 422 response missing 'detail'. body={data!r}"
    if not _detail_mentions_param(detail, param_name):
        return (
            f"STS GET {url}: 422 detail should identify out-of-range "
            f"'{param_name}'. detail={detail!r}"
        )

    logger.info(
        "PASS skip_limit_bounds path=%s param=%s status=%s",
        path,
        param_name,
        res.status_code,
    )
    return None


@pytest.mark.skip_limit_bounds
def test_oversized_skip_or_limit_returns_422(api_client: APIClient):
    """
    Oversized integer skip/limit on all in-scope list paths must yield 422, not 500.

    One pytest case: probe every discovered (path, skip|limit) pair, then fail once
    with an aggregated report if any probe misbehaves.
    """
    targets = _collect_targets()
    if not targets:
        pytest.skip("No skip/limit list paths discovered (spec missing or empty discovery)")

    failures: list[str] = []
    for path, param_name in targets:
        err = _probe_failure(api_client, path, param_name)
        if err:
            failures.append(err)

    print(f"\n--- skip_limit_bounds summary: {len(targets)} probes, {len(failures)} failed ---")
    assert not failures, (
        f"{len(failures)} of {len(targets)} oversized skip/limit probe(s) failed "
        f"(expected HTTP 422 with detail naming the param):\n"
        + "\n".join(f"  - {msg}" for msg in failures)
    )
