#!/usr/bin/env bash
# Run the three main report pipelines in sequence (fail-fast on first error).
# Order: manual pytest + HTML, then OpenAPI functional suite per model, then term-verify.
# No arguments are forwarded; use each script alone for -m nullcde, STS_MODELS, --warn-only, etc.
#
# Usage (from project root):
#   bash scripts/run_full_suite.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "=== 1/3 run_manual_tests.sh (manual pytest + pytest-html) ==="
bash scripts/run_manual_tests.sh

echo "=== 2/3 run_autogenerated_tests.py (CLI per model, HTML + JSON) ==="
python3 scripts/run_autogenerated_tests.py

echo "=== 3/3 run_all_term_verify.sh (all term_verify scripts) ==="
bash scripts/run_all_term_verify.sh

echo "=== Full suite finished successfully. ==="
